spring:
  profiles:
    active:
    - dog
    - dev
server:
  port: 8081
company:
    name: RSPLTD
mydatasource: 
        username: prouser
        password: propass
---
spring:
  config:
    name: dev
mydatasource: 
        username: devuser
        password: devpass 
server:
  port: 9876